language: python
sudo: required
python:
- '2.7'
install:
- travis_retry pip install tox>=2.1.1 coveralls
script:
- tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . )
after_success: coveralls --verbose
branches:
  only:
  - master
  - /^v.*$/
deploy: 
notifications:
  slack:
    secure: lyZnPtIMMrWtNI/3lKKoq9rW/4DFEwiM+BQ5lZAMK0dUUBLprfohbYPFgQs0hFGSWXRzZBxdvJQy11N0WHY39lcPvyBOCMz5r8yBnJjoFSte2J0DPyDDJgIsqtgkBGve8nAuxbDF1NxvJV5kTXXqbTJf3ugZVzu859L+kDjT8auNnyTAJDrkNWY5ZPY7GxgYL5nSgwh5RH634kifq+CHkaMxXUzIwcS9I0Q4adJgwsyywTOFU2wcDNg9ogTsLMU/bnD/1qOQEF2CmJQcsQZfgBEDN2K9rZztv2KN9crzKhXSoUYvYVcXYmdpqcSyVCTDtlXcq/4Fu5KLMtGx0mF+RZmzvbEF2o8Ou1hgyUsBhT+SDRkI7aBIxNENuIxDgmt1e1FFJD5fipBzFbNN1RiImZw/UBjHdJPeAOHjcnFt2TTGl1/mjMpk2H2ewa0GdFp/D4cK6u20RCyYi9f8Hx1T9YvtQva5TxsRNxsg1k6T1eDVyUoDz8118vZdji57VSfx3Vabh5SMdQSlomUS4woV/BAs2lVPzH6A0vhuwWDSSaT4qobelaB+tWrQsBfSqXsqfv8bQ4WIFePhjrycZKQ7JNMBVgCdayGf7rNSphnCzu/d/j2fSy64umkBIakjdEi3QKfVSbx4EBC6o+DxiVjciMeadG/yJTnDwotQraNV3gw=
